### ISSUE TITLE
Sort classrooms by room number and add busy flag

### ISSUE THREAD

**Issue by Scott-Kenning** [Scott-Kenning/StudySpaceFinder#39]

**Comment by hn275** [comment]
@Scott-Kenning pull uvic-api-go and check into the `fix-algo` branch, let me know if this type would work:

```typescript
type Room = {
    id: number;
    room: string;
    next_class: Session | null;
    current_class: Session | null;
};

type Session = {
    id: number;
    subject: string;
    description: string;
    time_start: string;
    time_end: string;
};
```

I'm thinking instead of a busy boolean, you can just evaluate
`current_class === null`, and if both are null then that class room is free til EOD

Rebuild the docker image if needed
